version: '3.8'

services:
  mysql:
    image: mysql:8.0.33
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: topicos
    ports:
      - "3306:3306"
    networks:
      - my-network

  spring-app:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      # SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/topicos?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/topicos
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on: 
      - mysql
    ports:
      - "8080:8080"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge