@URL=http://localhost:8080/atuador

### CREATE
POST {{URL}}
Content-Type: application/json

{
    "nome": "Jucasauro Franciscon"
}

### GET ALL
GET {{URL}}

### GET BY ID
GET {{URL}}/2


### UPDATE
PUT {{URL}}/2
Content-Type: application/json

{
    "nome": "Marcelo Alberton"
}

### DELETE
DELETE {{URL}}/2